#!/bin/sh

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
TEX_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
OUTPUT_FILE="$SCRIPT_DIR/full.tex"
OUTPUT_PDF="$SCRIPT_DIR/full.pdf"

resolve_input_path() {
  child=$1

  case "$child" in
    *.tex) child_name=$child ;;
    *) child_name=$child.tex ;;
  esac

  if [ -f "$current_dir/$child_name" ]; then
    printf '%s\n' "$current_dir/$child_name"
    return
  fi

  if [ -f "$TEX_DIR/$child_name" ]; then
    printf '%s\n' "$TEX_DIR/$child_name"
    return
  fi

  return 1
}

rewrite_paths() {
  sed \
    -e 's/{figures\//{..\/tex\/figures\//g' \
    -e 's/{references\//{..\/tex\/references\//g'
}

expand_file() {
  (
    input_path=$1
    current_dir=$(dirname "$input_path")

    printf '%% BEGIN FILE: %s\n' "${input_path#$TEX_DIR/}"

    while IFS= read -r line || [ -n "$line" ]; do
      case "$line" in
        \\input\{*\})
          child=${line#\\input\{}
          child=${child%\}}
          if ! child_path=$(resolve_input_path "$child"); then
            printf 'Missing input file for \\input{%s}\n' "$child" >&2
            exit 1
          fi

          expand_file "$child_path"
          ;;
        *)
          printf '%s\n' "$line" | rewrite_paths
          ;;
      esac
    done < "$input_path"

    printf '%% END FILE: %s\n' "${input_path#$TEX_DIR/}"
  )
}

{
  printf '%% Auto-generated by %s on %s\n' "$(basename "$0")" "$(date '+%Y-%m-%d %H:%M:%S')"
  printf '%% Source root: %s\n\n' "$TEX_DIR"
  expand_file "$TEX_DIR/main.tex"
} > "$OUTPUT_FILE"

printf 'Wrote %s\n' "$OUTPUT_FILE"

rm -f \
  "$SCRIPT_DIR/full.aux" \
  "$SCRIPT_DIR/full.bbl" \
  "$SCRIPT_DIR/full.blg" \
  "$SCRIPT_DIR/full.fdb_latexmk" \
  "$SCRIPT_DIR/full.fls" \
  "$SCRIPT_DIR/full.log" \
  "$SCRIPT_DIR/full.out" \
  "$SCRIPT_DIR/full.run.xml" \
  "$OUTPUT_PDF"

cd "$SCRIPT_DIR"

latexmk \
  -pdf \
  -interaction=nonstopmode \
  "$(basename "$OUTPUT_FILE")"

printf 'Wrote %s\n' "$OUTPUT_PDF"
